---
title: "The Algorithm of Coxtrans"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{coxtrans-algorithm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(MASS)
library(dplyr)
library(simsurv)
library(survtrans)
```

## Examples

```{r}
n_groups <- 10
n_samples <- 100
n_features <- 10

mu <- rep(0, n_features)
sigma <- diag(n_features)
beta <- rep(1, n_features)
names(beta) <- paste0("X", 1:n_features)
etas <- rbind(
  c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  c(-2, 0, -2, 0, -2, 0, -2, 0, -2, 0)
)
lambdas <- c(1 / 3, 1 / 2)
gammas <- c(3, 2)

covs <- c()
times <- c()
for (k in 1:n_groups) {
  cov <- data.frame(
    id = 1:n_samples, mvrnorm(n_samples, mu = mu, Sigma = sigma)
  )
  time <- simsurv(
    lambdas = lambdas[k %% 2 + 1], gammas = gammas[k %% 2 + 1],
    x = cov, betas = beta + etas[k %% 2 + 1, ], maxt = 3
  )
  cov$group <- k
  time$group <- k
  covs <- rbind(covs, cov)
  times <- rbind(times, time)
}

data <- left_join(covs, times, by = c("id", "group"))
```
