---
title: "The Generation of Simulated Survival Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{coxtrans-algorithm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(MASS)
library(dplyr)
library(simsurv)
```

## Examples

### Example 1: Homogeneous Baseline Hazard Function and Heterogeneous Effects

```{r}
n_features <- 10
n_samples_source <- 900
n_samples_target <- 100

mu <- rep(0, n_features)
sigma <- diag(n_features)
beta <- rep(1, n_features)
names(beta) <- paste0("X", 1:n_features)
eta <- c(0.5, rep(0, n_features - 1))

cov_source <- data.frame(
  id = 1:n_samples_source, mvrnorm(n_samples_source, mu = mu, Sigma = sigma)
)
time_source <- simsurv(
  lambdas = 1 / 3, gammas = 3, x = cov_source, betas = beta, maxt = 3
)
cov_source$group <- 1
time_source$group <- 1

cov_target <- data.frame(
  id = 1:n_samples_target, mvrnorm(n_samples_target, mu = mu, Sigma = sigma)
)
time_target <- simsurv(
  lambdas = 1 / 3, gammas = 3, x = cov_target, betas = beta + eta, maxt = 3
)
cov_target$group <- 2
time_target$group <- 2

covs <- rbind(cov_source, cov_target)
times <- rbind(time_source, time_target)
sim1 <- left_join(covs, times, by = c("id", "group")) %>%
  rename(time = "eventtime") %>%
  mutate(id = seq_len(nrow(.))) %>%
  select(id, group, time, status, X1:X10)
```

### Example 2: Heterogeneous Baseline Hazard Function and Heterogeneous Effects

```{r}
n_groups <- 10
n_samples <- 100
n_features <- 10

mu <- rep(0, n_features)
sigma <- diag(n_features)
beta <- rep(c(1, 0), n_features / 2)
names(beta) <- paste0("X", 1:n_features)
etas <- rbind(
  rep(c(0, 1), n_features / 2),
  rep(c(0, -1), n_features / 2)
)
lambdas <- c(1 / 3, 1 / 2)
gammas <- c(3, 2)

covs <- c()
times <- c()
for (k in 1:n_groups) {
  cov <- data.frame(
    id = 1:n_samples, mvrnorm(n_samples, mu = mu, Sigma = sigma)
  )
  time <- simsurv(
    lambdas = lambdas[k %% 2 + 1], gammas = gammas[k %% 2 + 1],
    x = cov, betas = beta + etas[k %% 2 + 1, ], maxt = 3
  )
  cov$group <- k
  time$group <- k
  covs <- rbind(covs, cov)
  times <- rbind(times, time)
}

sim2 <- left_join(covs, times, by = c("id", "group")) %>%
  rename(time = "eventtime") %>%
  mutate(id = seq_len(nrow(.))) %>%
  select(id, group, time, status, X1:X10)
```

## Other Examples

### Example Sparsity: Sparse Effects

```{r}
n_features <- 10
n_samples <- 1000

mu <- rep(0, n_features)
sigma <- diag(n_features)
beta <- c(1, 0.5, rep(0, n_features - 2))
names(beta) <- paste0("X", 1:n_features)

covs <- data.frame(
  id = 1:n_samples, mvrnorm(n_samples, mu = mu, Sigma = sigma)
)
times <- simsurv(
  lambdas = 1 / 3, gammas = 3, x = covs, betas = beta, maxt = 3
)

sim_sparse <- left_join(covs, times, by = "id") %>%
  rename(time = "eventtime") %>%
  mutate(id = seq_len(nrow(.))) %>%
  select(id, time, status, X1:X10)
```
